### PR TITLE
setup proper paths for gtk pixbuf

### LINKED ISSUE #3: segfault on manjaro
I have spacemacs setup, it only happens during edits. I noticed that the snap is reaching out to the system for gdk-pixbuf.

```
~/.../snapcore/snapcraft >>> emacs                               ±[ubuntu-eoan]
Gtk-Message: 16:23:59.254: Failed to load module "canberra-gtk-module"
Fontconfig warning: "/etc/fonts/fonts.conf", line 5: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/fonts.conf", line 6: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/fonts.conf", line 6: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/fonts.conf", line 6: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/fonts.conf", line 7: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/fonts.conf", line 7: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/fonts.conf", line 9: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/30-metric-aliases.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/30-metric-aliases.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/30-metric-aliases.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/30-metric-aliases.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/40-nonlatin.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/40-nonlatin.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/40-nonlatin.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/40-nonlatin.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/45-generic.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/45-generic.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/45-generic.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/45-generic.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/45-latin.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/45-latin.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/45-latin.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/45-latin.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/49-sansserif.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/49-sansserif.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/49-sansserif.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/49-sansserif.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/50-user.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/50-user.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/50-user.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/50-user.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/51-local.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/51-local.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/51-local.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/51-local.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/60-generic.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/60-generic.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/60-generic.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/60-generic.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/60-latin.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/60-latin.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/60-latin.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/60-latin.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-fonts-persian.conf", line 34: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/65-fonts-persian.conf", line 35: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/65-fonts-persian.conf", line 35: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/65-fonts-persian.conf", line 35: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/65-fonts-persian.conf", line 36: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/65-fonts-persian.conf", line 36: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/65-nonlatin.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/65-nonlatin.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/65-nonlatin.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/65-nonlatin.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/69-unifont.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/69-unifont.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/69-unifont.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/69-unifont.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/69-unifont.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/69-unifont.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/80-delicious.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/80-delicious.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/80-delicious.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/80-delicious.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/80-delicious.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/80-delicious.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'version'
Fontconfig error: Cannot load config file from /etc/fonts/fonts.conf
/usr/lib/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/gio/modules/libgioremote-volume-monitor.so

(emacs:32057): GdkPixbuf-WARNING **: 16:23:59.283: Cannot open pixbuf loader module file '/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.

(emacs:32057): GdkPixbuf-WARNING **: 16:23:59.577: Cannot open pixbuf loader module file '/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.

(emacs:32057): GdkPixbuf-WARNING **: 16:23:59.577: Cannot open pixbuf loader module file '/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.

(emacs:32057): GdkPixbuf-WARNING **: 16:23:59.577: Error loading XPM image loader: Image type 'xpm' is not supported

(emacs:32057): GdkPixbuf-WARNING **: 16:24:30.088: Cannot open pixbuf loader module file '/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.

(emacs:32057): Gtk-WARNING **: 16:24:30.088: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

(emacs:32057): GdkPixbuf-WARNING **: 16:24:30.088: Cannot open pixbuf loader module file '/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/gnome/16x16/status/image-missing.png: Unrecognised image file format (gdk-pixbuf-error-quark, 3)
Fatal error 6: Aborted
Backtrace:
/snap/emacs/43/usr/bin/emacs[0x58f02c]
/snap/emacs/43/usr/bin/emacs[0x567c21]
/snap/emacs/43/usr/bin/emacs[0x58e767]
/snap/emacs/43/usr/bin/emacs[0x58e738]
/snap/emacs/43/usr/bin/emacs[0x58e7a2]
/snap/core18/current/lib/x86_64-linux-gnu/libpthread.so.0(+0x12890)[0x7fd3ac80b890]
/snap/core18/current/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7fd3abb46e97]
/snap/core18/current/lib/x86_64-linux-gnu/libc.so.6(abort+0x141)[0x7fd3abb48801]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libglib-2.0.so.0(g_assertion_message+0x1b5)[0x7fd3b0d9a0b5]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libglib-2.0.so.0(g_assertion_message_error+0xae)[0x7fd3b0d9a8fe]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1f68dd)[0x7fd3b22ec8dd]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1f6fb7)[0x7fd3b22ecfb7]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1f70e4)[0x7fd3b22ed0e4]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1f72c8)[0x7fd3b22ed2c8]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(+0x20a5cd)[0x7fd3b23005cd]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(+0x16f393)[0x7fd3b2265393]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1734a1)[0x7fd3b22694a1]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(+0x20ad23)[0x7fd3b2300d23]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2d1651)[0x7fd3b23c7651]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2d18ec)[0x7fd3b23c78ec]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0xb5)[0x7fd3b23c7bf5]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(+0x11fb86)[0x7fd3b2215b86]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(+0x16f393)[0x7fd3b2265393]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1734a1)[0x7fd3b22694a1]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(+0x1204e3)[0x7fd3b22164e3]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2d1651)[0x7fd3b23c7651]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2d18ec)[0x7fd3b23c78ec]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_height+0x91)[0x7fd3b23c6e11]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(+0x391222)[0x7fd3b2487222]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2d10dc)[0x7fd3b23c70dc]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2d18ec)[0x7fd3b23c78ec]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_widget_get_preferred_height_and_baseline_for_width+0xb5)[0x7fd3b23c7bf5]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(+0x2d1d33)[0x7fd3b23c7d33]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(+0x393344)[0x7fd3b2489344]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(+0x393d26)[0x7fd3b2489d26]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x10346)[0x7fd3b105a346]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0xd5f)[0x7fd3b107596f]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x8f)[0x7fd3b107609f]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgtk-3.so.0(+0x395db5)[0x7fd3b248bdb5]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x19d)[0x7fd3b105a10d]
/var/lib/snapd/snap/emacs/43/usr/bin/../lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x2309e)[0x7fd3b106d09e]
...
zsh: abort (core dumped)  emacs
```

### PR DESCRIPTION
**Pull request by sergiusens**
Achieve this by use of command-chain and getting rid of the
wrappers.

Fixes #3

Signed-off-by: Sergio Schvezov <sergio.schvezov@canonical.com>

### CODE REVIEW

**Comment by alexmurray** [comment]
This failed for me:

```
$ emacs
/snap/emacs/x1/gtk-launch: 3: [: amd64: unexpected operator
/snap/emacs/x1/gtk-launch: 5: [: amd64: unexpected operator
/snap/emacs/x1/gtk-launch: 7: [: amd64: unexpected operator

(emacs:1212): GdkPixbuf-WARNING **: 13:04:53.967: Error loading XPM image loader: Unable to load image-loading module: /snap/emacs/x5/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-xpm.so: /snap/emacs/x5/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-xpm.so: cannot open shared object file: No such file or directory
```

However, if I changed the interpreter to `#!/bin/bash` in `gtk-launch`  (rather than `#!/bin/sh`) then it seems to run without error.

**Comment by sergiusens** [comment]
Interesting, let me run shellcheck against it, FWIW I built the snap locally with what I presented in this PR and running just fine. Now I see why:

```
sergiusens@gotham Linux 5.2.11-1-MANJARO x86_64 19.08.14 Juhraya
~ >>> ls /bin/sh -l                                                             
lrwxrwxrwx 1 root root 4 ago 20 12:12 /bin/sh -> bash
```

**Comment by alexmurray** [comment]
```
$ shellcheck gtk-launch 

In gtk-launch line 3:
if [ "$SNAP_ARCH" == "amd64" ]; then
                  ^-- SC2039: In POSIX sh, == in place of = is undefined.


In gtk-launch line 5:
elif [ "$SNAP_ARCH" == "armhf" ]; then
                    ^-- SC2039: In POSIX sh, == in place of = is undefined.


In gtk-launch line 7:
elif [ "$SNAP_ARCH" == "arm64" ]; then
                    ^-- SC2039: In POSIX sh, == in place of = is undefined.

```

**Comment by alexmurray** [comment]
```
$ checkbashisms gtk-launch 
possible bashism in gtk-launch line 3 (should be 'b = a'):
if [ "$SNAP_ARCH" == "amd64" ]; then
possible bashism in gtk-launch line 5 (should be 'b = a'):
elif [ "$SNAP_ARCH" == "armhf" ]; then
possible bashism in gtk-launch line 7 (should be 'b = a'):
elif [ "$SNAP_ARCH" == "arm64" ]; then
```

**Comment by alexmurray** [comment]
So either change the interpreter to `bash` or change the `==` for `=` and keep `sh` as the interpreter I guess.

**Comment by sergiusens** [comment]
Thanks @alexmurray, I made it _more than bash_ compatible

**Comment by alexmurray** [comment]
Nice - thanks.

**Pull request merged**
