### PR TITLE
Update setup-env to set `XDG_DATA_DIRS` for old systems

### LINKED ISSUE #80: emacs snap 29.1 requires manual glib-2.0 schema files on old systems
while running on old rhel7 systems, the snap manages to execute,
but if you try to use file chooser dialog, there is an issue:
Sun Dec 10 2023 09_45_55 GMT+0200 (Israel Standard Time)

After further digging:
1. there is an issue with `glib-2.0` schema files mismatch
2. the correct schema files are shipped with the package
3. if I run: `snap run --shell emacs`, and then inspect `XDG_DATA_DIRS`, the variable lacks any that snap specific folders

Workaround without changing the snap:
1. copy the schema files to system location, e.g. as root:
```
cp /snap/emacs/2307/usr/share/glib-2.0/schemas/org.gtk.Settings.FileChooser.gschema.xml /usr/share/glib-2.0/schemas`
```
2. restart the snap application

I am noticing that newer versions of snap, e.g. version `30.0.50-master-a470dfb` already has `XDG_DATA_DIRS` with the right snap folder.

Can you please repackage the snap for 29.1  with the same fix ?

### PR DESCRIPTION
**Pull request by mvk**
resolve #80

### CODE REVIEW

**Comment by mvk** [comment]
@alexmurray , please comment, and hopefully merge 🙏

**Comment by alexmurray** [comment]
Thanks - I've retargetted this to the master branch which is where stable builds of the snap come from.

**Comment by mvk** [comment]
> Thanks - I've retargetted this to the master branch which is where stable builds of the snap come from.

Thank you, @alexmurray , the issue is not in `master` nor in `pgtk`,
It is only for the `emacs-29` branch.

**Comment by alexmurray** [comment]
The emacs-29 branch is not used anymore - as you can see at https://launchpad.net/~alexmurray/+snap/emacs the master branch gets published to the beta channel in the store and then I manually promote that to stable. So if this is not needed on master (ie if the current stable emacs snap does not need this change) then this PR should be closed.

**Pull request closed without merging**
