### PR TITLE
Update tree-sitter part to latest upstream release "v0.22.6"

### LINKED ISSUE #89: Update tree-sitter for compatibility with newer tree-sitter grammars
As detailed in https://github.com/tree-sitter/tree-sitter/issues/3296 – tree-sitter >=0.22.4 has introduced an ABI break that renders tree-sitter grammars depending on tree-sitter >=0.22.4 incompatible with Emacsen linked against an older tree-sitter version.

As the Emacs snap uses tree-sitter `v0.20.9`, the result is that most grammars that use the newer ABI do not work OOTB when installing with `M-x treesit-install-language-grammar`. Notably, this affects tree-sitter-go, which depends on the newer ABI since https://github.com/tree-sitter/tree-sitter-go/commit/174bc4405b312fde1c5d78468fccf0ad27e41617 and no longer works on the Emacs snap OOTB.

On #emacs and on the tree-sitter issue board, the general consensus is that distributors should rebuild all consumers of tree-sitter for new versions. I think that may be worth considering for the Emacs snap, especially given that a) most grammars have switched to the new ABI and b) a newer tree-sitter is necessary to make use of them.

### PR DESCRIPTION
**Pull request by fapdash**
Closes #89

### CODE REVIEW

**Comment by fapdash** [comment]
@fmqa Can you please verify that this fixes your problem by following https://github.com/alexmurray/emacs-snap?tab=readme-ov-file#build-it-yourself?

**Comment by alexmurray** [comment]
Thanks for this but as far as I know upgrading tree-sitter may break the use of tree-sitter modules that folks are using - ie. if they have already compiled a tree-sitter module and we upgrade tree-sitter in emacs to a newer version, they would need to recompile their modules - can you confirm if this is expected to work with the older version of tree-sitter as we currently use in the emacs snap?

**Comment by alexmurray** [comment]
Ok I have just done a local test rebuild which includes this new tree-sitter version and it appears to work with the existing modules that I had compiled locally.

**Comment by alexmurray** [comment]
Now that we have 29.4 with the older tree-sitter in the stable channel, I will merge this and let it sit in the beta channel for a bit to get some testing before we go and publish it to stable.

**Comment by fmqa** [comment]
@fapdash @alexmurray Thanks for the PR+Merge & sorry for the delayed reply. I have actually tested this change a while ago with the tree-sitter modes I use and it works as expected. FWIW, I only use `go-ts-mode` and `gomod-ts-mode` but I believe it should work with all other tree-sitter modes too.

Re: Recompiling tree-sitter modules – this might indeed become a recurring problem, since tree-sitter unfortunately lacks a stable ABI. In this case luckily it seems only forward-compatibility was affected, but rebuilding with a newer tree-sitter may be again required if tree-sitter breaks ABI again.

**Pull request merged**
